apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: example-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-backend
    spec:
      containers:
        - name: example-backend
          image: localhost:5001/example-backend:0.2.0
          ports:
            - containerPort: 8080
