apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - sealedsecret.yaml

configMapGenerator:
  - name: example-backend
    literals:
      - GREETING_MESSAGE=Hello after config change
      - QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector.observability.svc:4317
