---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: example-backend
  namespace: default
spec:
  encryptedData:
    GREETING_SECRET: AgCIQnQ3p0GUSuBF/4pCeNZhOjav0XvOyufDJK/uHlV0BR5C/ZFbCln1B60wyjlgZWR8NZjhU/3LCo+j1McTiPONp+LvEIVw9rDUUs0lBWpFp5uc4OLKu2G/vUIMXnRA+e1DnX3LrX884tuu9Wp2XJmXPtkDNHzAdO7QYGQ32Rj5hdAKWMx5nWy6n25PBdAPOS+i0hV/AVff6vebV1oB2xcd17DcPQsFniym1wq99CP8eXjjQ3M392xKa3TEvPucUMqcu7AsXZsTGY4qwN+M8yKf6ULHCmYj2bMIxyax6Gsc16XpCG3u4anmLHB6Izk5HCcDQElnAJDDpVuYCF0e05TpSeyiODxpVvxC6BMvD6yUM4huxPqn/cqy80PgNl2gLin2p7DoaWtXx41ucYZJZHX1M4a+Owo723ElB9EWVcKeOCKDkMc1gOqXzvYnzcavS+MkzEqaahI5ma2jMXFLghrkXf9yVCt+gz3j+BTJCBUAQohuxe/mFpE9AADA9KCUWj1Zi/B7Wr35XECmPbpXGHv4o0UApKVXu3Hs5QUAmi2uia7UJ63lljgJ3sT19XJvr8bojosS3FrgyFmohdsTyg9YK6lK2fKOhbGfp7nLo1gBIPUk62Tqy4VW8B8QLpXnbPck3Moa9ut/kbn8njHKn80mAhBAsplQCWCJklzXS4Zw+meYPn3MZhZHgOTOaiTuidoYp48XFw3YaUSx/31+nRt4E9wd4Y8rUpk=
  template:
    metadata:
      name: example-backend
      namespace: default
    type: Opaque
